name: byhand
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: openjdk@1.17.0
      - name: Compile
        run: sbt test
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: sbt tests            # Name of the check run which will be created
          path: target/test-reports/**/*.xml    # Path to test results
          reporter: java-junit        # Format of test results
